import test from 'node:test';
import assert from 'node:assert/strict';
import { generateKeyPairSync, sign, randomUUID } from 'node:crypto';


delete process.env.TABLE_NAME;delete process.env.AWS_LAMBDA_FUNCTION_NAME;
process.env.NODE_ENV='test';process.env.DATA_MODE='memory';
process.env.COGNITO_ISSUER='https://cognito-idp.sa-east-1.amazonaws.com/test-pool';process.env.COGNITO_CLIENT_ID='synthetic-client';process.env.AUTH_COMPANY_CLAIM='custom:empresa_id';
const { hash }=await import('../src/services/biometria.service.js');
const {handler}=await import('../src/lambda.js');const store=await import('../src/db/store.js');
const PNG='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=';
const pair=generateKeyPairSync('ec',{namedCurve:'prime256v1'}),publicKey=pair.publicKey.export({type:'spki',format:'der'}).toString('base64');
const template='SYNTHETIC_TEMPLATE_FOR_PROTOCOL_TEST_ONLY_'.repeat(3);
const claims={sub:'synthetic-operator',iss:process.env.COGNITO_ISSUER,aud:process.env.COGNITO_CLIENT_ID,exp:String(Math.floor(Date.now()/1000)+3600),token_use:'id','cognito:groups':'[MASTER]'};
async function request(method,path,body,company,auth=claims){const r=await handler({version:'2.0',routeKey:'ANY /{proxy+}',rawPath:path,rawQueryString:'',headers:{host:'synthetic.invalid','content-type':'application/json',...(company?{'x-empresa-id':company}:{})},requestContext:{requestId:randomUUID(),stage:'$default',http:{method,path,protocol:'HTTP/1.1',sourceIp:'127.0.0.1'},...(auth?{authorizer:{jwt:{claims:auth}}}:{})},isBase64Encoded:false,...(body?{body:JSON.stringify(body)}:{})},{});return {status:r.statusCode,body:JSON.parse(r.body)};}
function attestation(challenge,changes={}){const proof=JSON.stringify({v:1,kind:challenge.kind,challengeId:challenge.challengeId,workerId:challenge.workerId,fichaId:challenge.fichaId,fingerCode:challenge.fingerCode,templateHash:hash(template),...(challenge.kind==='enroll'?{enrolled:true,imageHash:hash(Buffer.from(PNG.split(',')[1],'base64'))}:{matched:true,imageHash:hash(Buffer.from(PNG.split(',')[1],'base64'))}),...changes});return {challengeId:challenge.challengeId,template,publicKey,fingerImageDataUrl:PNG,proof,proofSignature:sign('sha256',Buffer.from(proof),pair.privateKey).toString('base64')};}
async function fixture(){const company=await store.create('empresa',{nome:'EMPRESA SINTÉTICA'});const worker=await store.create('trabalhador',{empresaId:company.id,nomeCompleto:'TRABALHADOR SINTÉTICO',cpf:'00000000000',matriculaESocial:'00A',funcao:'TESTE',localidade:'TESTE',status:'Ativo'});const ficha=await store.create('ficha',{empresaId:company.id,trabalhadorId:worker.id,status:'pendente',itens:[{quantidade:1,epiNome:'CAPACETE'}]});return {company,worker,ficha};}
async function enroll(f){const r=await request('POST',`/api/trabalhadores/${f.worker.id}/biometria/desafio`,{fingerCode:'R_INDEX'},f.company.id);assert.equal(r.status,200);const body=attestation(r.body.challenge);const saved=await request('POST',`/api/trabalhadores/${f.worker.id}/biometria`,body,f.company.id);assert.equal(saved.status,200);return body;}
async function verification(f){const r=await request('POST',`/api/fichas/${f.ficha.id}/biometria/desafio`,{fingerCode:'R_INDEX'},f.company.id);assert.equal(r.status,200);return attestation(r.body.challenge);}
const finish=(f,body,auth=claims,company=f.company.id)=>request('POST',`/api/fichas/${f.ficha.id}/assinar`,body,company,auth);

test('imagem sem comparação, booleanos forjados e dedo não cadastrado não assinam',async()=>{const f=await fixture();assert.equal((await finish(f,{fingerImageDataUrl:PNG,verificada:true,matched:true})).status,403);assert.equal((await request('POST',`/api/fichas/${f.ficha.id}/biometria/desafio`,{fingerCode:'R_INDEX'},f.company.id)).status,409);assert.equal((await store.get('ficha',f.ficha.id)).status,'pendente');});
test('cadastro separado da listagem; template não aparece no cadastro de trabalhadores',async()=>{const f=await fixture();const body=await enroll(f);assert.equal((await request('POST',`/api/trabalhadores/${f.worker.id}/biometria`,body,f.company.id)).body.replayed,true);const list=await request('GET','/api/trabalhadores',null,f.company.id);assert.equal(list.body.items[0].biometrias.R_INDEX.id.length,64);assert.equal(JSON.stringify(list.body).includes(template),false);});
test('conferência positiva assina, preserva prova e permite reenvio idempotente',async()=>{const f=await fixture();await enroll(f);const body=await verification(f);const first=await finish(f,body),again=await finish(f,body);assert.equal(first.status,200);assert.equal(first.body.item.assinaturaBiometrica.verificada,true);assert.equal(first.body.item.assinaturaBiometrica.metodo,'NITGEN_VERIFY_MATCH');assert.equal(again.body.replayed,true);assert.equal(first.body.item._version,again.body.item._version);});
test('digital divergente permanece pendente, sem imagem salva',async()=>{const f=await fixture();await enroll(f);const body=await verification(f);const p=JSON.parse(body.proof);const r=await finish(f,attestation({...p,challengeId:p.challengeId},{matched:false}));assert.equal(r.status,422);const item=await store.get('ficha',f.ficha.id);assert.equal(item.status,'pendente');assert.equal(item.assinaturaBiometrica,undefined);});
test('prova forjada, imagem adulterada e template trocado são rejeitados',async()=>{const f=await fixture();await enroll(f);const body=await verification(f);assert.equal((await finish(f,{...body,proof:body.proof.replace('R_INDEX','R_THUMB')})).status,400);assert.equal((await finish(f,{...body,fingerImageDataUrl:PNG.replace('A5','B5')+'A'})).status,400);const p=JSON.parse(body.proof);assert.equal((await finish(f,attestation({...p,challengeId:p.challengeId},{templateHash:'0'.repeat(64)}))).status,400);assert.equal((await store.get('ficha',f.ficha.id)).status,'pendente');});
test('empresa, ator, trabalhador e ficha precisam corresponder ao desafio',async()=>{const f=await fixture(),g=await fixture();await enroll(f);const body=await verification(f);assert.equal((await finish(f,body,null)).status,401);assert.equal((await finish(f,body,claims,g.company.id)).status,403);assert.equal((await finish(f,body,{...claims,sub:'outro'})).status,403);assert.equal((await finish(g,body)).status,403);});
test('tentativa expirada e recadastro concorrente bloqueiam a assinatura antiga',async()=>{const f=await fixture();await enroll(f);const body=await verification(f);await store.update('biometria_desafio',body.challengeId,{expiresAtEpoch:1});assert.equal((await finish(f,body)).status,410);const next=await verification(f);await enroll(f);assert.equal((await finish(f,next)).status,409);});
test('alteração do trabalhador durante captura exige nova conferência',async()=>{const f=await fixture();await enroll(f);const body=await verification(f);await store.update('trabalhador',f.worker.id,{funcao:'ATUALIZADA'});assert.equal((await finish(f,body)).status,409);});
test('confirmações concorrentes preservam uma única assinatura',async()=>{const f=await fixture();await enroll(f);const first=await verification(f),second=await verification(f);const answers=await Promise.all([finish(f,first),finish(f,second)]);assert.deepEqual(answers.map(x=>x.status).sort(),[200,409]);assert.equal((await store.get('ficha',f.ficha.id))._version,2);});
test('exclusão de pendente remove; assinatura verificada exige motivo e mantém histórico cancelado',async()=>{const pending=await fixture();assert.equal((await request('DELETE',`/api/fichas/${pending.ficha.id}`,{},pending.company.id)).body.deleted,true);const f=await fixture();await enroll(f);await finish(f,await verification(f));assert.equal((await request('DELETE',`/api/fichas/${f.ficha.id}`,{},f.company.id)).status,400);const r=await request('DELETE',`/api/fichas/${f.ficha.id}`,{motivo:'TESTE'},f.company.id);assert.equal(r.body.item.status,'cancelada');assert.equal(r.body.item.assinaturaBiometrica.verificada,true);});
test('edição de trabalhador preserva empresa, rejeita versão obsoleta e duplicidade',async()=>{const f=await fixture();const path=`/api/trabalhadores/${f.worker.id}`;const r=await request('PATCH',path,{_version:1,nomeCompleto:'NOME EDITADO',matriculaESocial:'00Ab001'},f.company.id);assert.equal(r.status,200);assert.equal(r.body.item.matriculaESocial,'00Ab001');assert.equal((await request('PATCH',path,{_version:1,nomeCompleto:'OBSOLETO'},f.company.id)).status,409);assert.equal((await request('PATCH',path,{_version:2,empresaId:'outra'},f.company.id)).status,400);const other=await store.create('trabalhador',{...f.worker,cpf:'11111111111',matriculaESocial:'DUPLICADA'});assert.equal((await request('PATCH',path,{_version:2,matriculaESocial:other.matriculaESocial},f.company.id)).status,409);});

test('registro antigo sem conferência pode ser validado preservando a assinatura anterior',async()=>{const f=await fixture();await store.update('ficha',f.ficha.id,{status:'assinada',assinaturaBiometrica:{verificada:false,dedo:'R_INDEX',realFingerImage:PNG}});await enroll(f);const r=await finish(f,await verification(f));assert.equal(r.status,200);assert.equal(r.body.item.assinaturaBiometrica.verificada,true);assert.equal((await store.list('assinatura_anterior',f.company.id)).length,1);});

test('galeria retorna imagem autêntica sem template e bloqueia outra empresa',async()=>{const f=await fixture(),g=await fixture();await enroll(f);const path=`/api/trabalhadores/${f.worker.id}/biometrias`;const r=await request('GET',path,null,f.company.id);assert.equal(r.status,200);assert.deepEqual(Object.keys(r.body.items[0]).sort(),['enrolledAt','fingerCode','imageDataUrl']);assert.equal(r.body.items[0].imageDataUrl,PNG);assert.equal(JSON.stringify(r.body).includes(template),false);assert.equal((await request('GET',path,null,g.company.id)).status,403);const list=await request('GET','/api/trabalhadores',null,f.company.id);assert.equal(JSON.stringify(list.body).includes(PNG),false);});
test('cadastro rejeita imagem não vinculada à prova e aceita agente antigo sem inventar miniatura',async()=>{const f=await fixture();const start=await request('POST',`/api/trabalhadores/${f.worker.id}/biometria/desafio`,{fingerCode:'R_INDEX'},f.company.id);const wrong=attestation(start.body.challenge,{imageHash:'0'.repeat(64)});assert.equal((await request('POST',`/api/trabalhadores/${f.worker.id}/biometria`,wrong,f.company.id)).status,400);const legacy=attestation(start.body.challenge,{imageHash:undefined});delete legacy.fingerImageDataUrl;assert.equal((await request('POST',`/api/trabalhadores/${f.worker.id}/biometria`,legacy,f.company.id)).status,200);const gallery=await request('GET',`/api/trabalhadores/${f.worker.id}/biometrias`,null,f.company.id);assert.equal(gallery.body.items[0].imageDataUrl,'');});
test('excluir empresa preserva ficha assinada e bloqueia JWT existente, captura e edição',async()=>{const f=await fixture();await enroll(f);await finish(f,await verification(f));const before=await store.get('ficha',f.ficha.id);const body={confirmacao:f.company.nome,_version:f.company._version};const client={...claims,'cognito:groups':[], 'custom:empresa_id':f.company.id};assert.equal((await request('DELETE',`/api/empresas/${f.company.id}`,body,f.company.id,client)).status,403);assert.equal((await request('DELETE',`/api/empresas/${f.company.id}`,{...body,confirmacao:'errada'},f.company.id)).status,400);assert.equal((await request('DELETE',`/api/empresas/${f.company.id}`,{...body,_version:999},f.company.id)).status,409);assert.equal((await request('DELETE',`/api/empresas/${f.company.id}`,body,f.company.id)).status,200);assert.deepEqual(await store.get('ficha',f.ficha.id),before);assert.ok(await store.get('trabalhador',f.worker.id));assert.equal((await request('GET','/api/empresas',null,null,client)).status,403);assert.equal((await request('GET','/api/trabalhadores',null,f.company.id)).status,403);assert.equal((await request('POST',`/api/trabalhadores/${f.worker.id}/biometria/desafio`,{fingerCode:'R_INDEX'})).status,403);assert.equal((await request('PATCH',`/api/empresas/${f.company.id}`,{nome:'Reativar'})).status,403);const listing=await request('GET','/api/empresas');assert.equal(listing.body.items.some(x=>x.id===f.company.id),false);});

test('consulta pontual da assinatura retorna dados atuais e mantém autorização e identidade',async()=>{
 const f=await fixture(),g=await fixture();await enroll(f);const path=`/api/fichas/${f.ficha.id}/assinatura-contexto`;
 const r=await request('GET',path,null,f.company.id);assert.equal(r.status,200);assert.equal(r.body.ficha.id,f.ficha.id);assert.equal(r.body.worker.id,f.worker.id);assert.equal(JSON.stringify(r.body).includes(template),false);
 assert.equal((await request('GET',path,null,g.company.id)).status,403);assert.equal((await request('GET',path,null,f.company.id,null)).status,401);
 await store.update('trabalhador',f.worker.id,{nomeCompleto:'NOME ATUAL'});assert.equal((await request('GET',path,null,f.company.id)).body.worker.nomeCompleto,'NOME ATUAL');
 await store.update('ficha',f.ficha.id,{trabalhadorSnapshot:{cpf:'11111111111'}});assert.equal((await request('GET',path,null,f.company.id)).status,409);
});
