// Real UI + Lambda handler + in-memory store. Only reader and Cognito are simulated.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),http=require('node:http');
const {generateKeyPairSync,sign,randomUUID,createHash}=require('node:crypto');
const {chromium}=require('playwright');
process.env.NODE_ENV='test';process.env.DATA_MODE='memory';delete process.env.TABLE_NAME;delete process.env.AWS_LAMBDA_FUNCTION_NAME;
process.env.COGNITO_ISSUER='https://cognito-idp.sa-east-1.amazonaws.com/synthetic';process.env.COGNITO_CLIENT_ID='synthetic';process.env.AUTH_COMPANY_CLAIM='custom:empresa_id';
const output=path.join(__dirname,'output/operations');fs.mkdirSync(output,{recursive:true});
const frontend=path.resolve(__dirname,'../frontend/EntregaEPI');
const report={syntheticData:true,realApiUsed:false,physicalReader:false,checks:[]};
const pass=name=>{report.checks.push({name,passed:true});console.log('PASSOU: '+name);};
const server=http.createServer((req,res)=>{const file=path.resolve(frontend,decodeURIComponent(new URL(req.url,'http://localhost').pathname).replace(/^\/EntregaEPI\/?/,'')||'index.html');if(!file.startsWith(frontend+path.sep)||!fs.existsSync(file)){res.writeHead(404);res.end();return;}const ext=path.extname(file);res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png'})[ext]||'application/octet-stream');const data=fs.readFileSync(file);res.end(ext==='.html'?data.toString().replaceAll('__APP_PREFIX__','EntregaEPI'):data);});
const hash=x=>createHash('sha256').update(x).digest('hex');
const pair=generateKeyPairSync('ec',{namedCurve:'prime256v1'}),publicKey=pair.publicKey.export({type:'spki',format:'der'}).toString('base64');
const template='TEMPLATE_SINTETICO_SEM_DADOS_BIOMETRICOS_REAIS_'.repeat(3);
let browser,context,page,match=false,signWrites=0,errors=[],imageData;
(async()=>{
 const store=await import('../backend/src/db/store.js'),{handler}=await import('../backend/src/lambda.js');
 const company=await store.create('empresa',{nome:'EMPRESA DE DEMONSTRAÇÃO',cnpj:'00000000000000',localidade:'Dourados',uf:'MS',login:'demo',status:'Ativa',acessoStatus:'ativo'});
 const other=await store.create('empresa',{nome:'SEGUNDA EMPRESA',cnpj:'11111111111111',localidade:'Campo Grande',uf:'MS',status:'Ativa'});
 const worker=await store.create('trabalhador',{empresaId:company.id,nomeCompleto:'TRABALHADOR DE DEMONSTRAÇÃO',cpf:'00000000000',matriculaESocial:'00001A',funcao:'TÉCNICO DE TESTE',localidade:'Dourados/MS',status:'Ativo'});
 const epi=await store.create('epi',{ca:'365',nomeCurto:'CAPACETE DE SEGURANÇA',descricao:'Capacete de Segurança Tipo I Classe E, aba total com casco injetado. '.repeat(12),fabricante:'FABRICANTE DE TESTE'});
 const claims={sub:'MASTER-SINTETICO',iss:process.env.COGNITO_ISSUER,aud:'synthetic',exp:String(Math.floor(Date.now()/1000)+3600),token_use:'id','cognito:groups':['MASTER']};
 const token='header.'+Buffer.from(JSON.stringify(claims)).toString('base64url')+'.synthetic';
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin=`http://127.0.0.1:${server.address().port}`;
 browser=await chromium.launch({headless:true,args:['--no-sandbox']});context=await browser.newContext({viewport:{width:1440,height:1000},locale:'pt-BR',timezoneId:'America/Campo_Grande'});
 await context.addInitScript(()=>Object.defineProperty(navigator.permissions,'query',{value:async()=>({state:'granted'})}));
 context.on('page',p=>p.on('pageerror',e=>errors.push(e.message)));
 await context.route(url=>url.origin!==origin,async route=>{
   const request=route.request(),url=new URL(request.url()),json=(status,body)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(body)});
   if(url.hostname.startsWith('cognito-idp.'))return json(200,{AuthenticationResult:{IdToken:token,AccessToken:'synthetic',ExpiresIn:3600}});
   if(url.hostname==='127.0.0.1'){
     if(url.pathname==='/status')return json(200,{ok:true,service:'JP Biometria',version:'12.9.1',sdk:true,reader:true,deviceCount:1,capabilities:{capture:true,captureMethod:'POST',capturePath:'/api/capture',verify:true,templates:true}});
     if(['/api/enroll','/api/signature'].includes(url.pathname)){
       const body=request.postDataJSON();if(body.kind==='verify'&&!match)return json(422,{ok:false,code:'BIOMETRIA_DIVERGENTE'});
       const proof=JSON.stringify({v:1,kind:body.kind,challengeId:body.challengeId,workerId:body.workerId,fichaId:body.fichaId,fingerCode:body.fingerCode,templateHash:hash(template),...(body.kind==='enroll'?{enrolled:true,imageHash:hash(Buffer.from(imageData.split(',')[1],'base64'))}:{matched:true,imageHash:hash(Buffer.from(imageData.split(',')[1],'base64'))})});
       return json(200,{ok:true,proof,proofSignature:sign('sha256',Buffer.from(proof),pair.privateKey).toString('base64'),publicKey,...(body.kind==='enroll'?{template,fingerImageDataUrl:imageData}:{matched:true,realFingerImage:true,fingerImageDataUrl:imageData})});
     }throw new Error('Unexpected local route '+url.pathname);
   }
   assert.ok(url.hostname.endsWith('.execute-api.sa-east-1.amazonaws.com'));
   if(url.pathname==='/health')return json(200,{ok:true,durable:true,storageReady:true});
   if(url.pathname==='/api/caepi/365')return json(200,{ok:true,item:{ca:'365',name:'CAPACETE DE SEGURANÇA',description:epi.descricao,manufacturer:epi.fabricante,found:true,officialSnapshot:true,downloadedAt:'2026-10-06T16:00:00Z',autofillAllowed:true}});
   const headers=request.headers();if(url.pathname.endsWith('/assinar'))signWrites++;
   const r=await handler({version:'2.0',routeKey:'ANY /{proxy+}',rawPath:url.pathname,rawQueryString:url.search.slice(1),headers:{...headers,host:'synthetic.invalid'},requestContext:{requestId:randomUUID(),stage:'$default',http:{method:request.method(),path:url.pathname,protocol:'HTTP/1.1',sourceIp:'127.0.0.1'},authorizer:{jwt:{claims}}},isBase64Encoded:false,...(request.postData()?{body:request.postData()}:{})},{});
   return json(r.statusCode,JSON.parse(r.body));
 });
 page=await context.newPage();await page.goto(origin+'/EntregaEPI/');
 imageData=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=160;c.height=190;const x=c.getContext('2d');x.fillStyle='white';x.fillRect(0,0,c.width,c.height);x.fillStyle='#405d50';x.textAlign='center';x.font='bold 18px Arial';['AMOSTRA','SINTÉTICA','SEM VALIDADE'].forEach((s,i)=>x.fillText(s,80,70+i*25));return c.toDataURL('image/png');});
 await page.locator('#username').fill('MASTER-TESTE');await page.locator('#password').fill('SENHA-SINTETICA');await page.locator('#loginButton').click();await page.waitForFunction(()=>!document.getElementById('startupRetryButton').disabled);
 await page.locator('#empresaAtivaSelect').selectOption(company.id);await page.waitForFunction(id=>document.getElementById('entregaTrabalhador').querySelector(`option[value="${id}"]`),worker.id);
 assert.equal(await page.locator('#screen-dashboard .startup-checks').count(),0);assert.equal(await page.locator('.health-chip').count(),3);for(const chip of ['healthSystem','healthCA','healthBio'])assert.equal(await page.locator('#'+chip).getAttribute('data-state'),'success');
 await page.screenshot({path:path.join(output,'01-dashboard.png'),fullPage:true});await page.locator('#healthSystem').click();assert.equal(await page.locator('#screen-config .startup-checks').isVisible(),true);pass('Dashboard com três indicadores compactos; diagnósticos completos somente em Configurações');
 await page.evaluate(()=>goScreen('empresas'));await page.locator(`[data-edit-company="${company.id}"]`).click();await page.locator('#company-edit-responsavel').fill('RESPONSÁVEL DE TESTE');await page.locator('#companyEditForm button').click();await page.waitForSelector('dialog',{state:'detached'});assert.equal((await store.get('empresa',company.id)).responsavel,'RESPONSÁVEL DE TESTE');pass('Editar empresa salva os dados preservando CNPJ e acesso');
 await page.evaluate(()=>goScreen('trabalhadores'));await page.locator(`[data-edit-worker="${worker.id}"]`).click();await page.locator('#trabalhadorFuncao').fill('TÉCNICO ATUALIZADO');await page.locator('#trabalhadorMatricula').fill('0001Ab009');await page.locator('#trabalhadorForm button[type=submit]').click();await page.waitForFunction(()=>document.getElementById('workerFormTitle').textContent==='Novo trabalhador');assert.equal((await store.get('trabalhador',worker.id)).funcao,'TÉCNICO ATUALIZADO');pass('Editar trabalhador salva função e matrícula alfanumérica');
 await page.locator(`[data-worker-bio="${worker.id}"]`).click();await page.locator('#operationFinger').selectOption('R_INDEX');await page.locator('#enrollFingerprint').click();await page.waitForFunction(()=>document.querySelector('.dialog-message')?.textContent.includes('Digital cadastrada'));
 assert.equal(await page.locator('.bio-card img').count(),1);assert.equal(await page.locator('.bio-card img').getAttribute('src'),imageData);pass('Galeria exibe imagem da captura por dedo, sem substituir por imagem ilustrativa');
 await page.locator('dialog').screenshot({path:path.join(output,'02-cadastro-digital.png')});await page.locator('.dialog-close').click();assert.match(await page.locator(`[data-worker-bio="${worker.id}"]`).innerText(),/1/);pass('Cadastro prévio de digital em painel compacto do trabalhador');
 await page.evaluate(()=>goScreen('entrega'));await page.locator('#entregaTrabalhador').selectOption(worker.id);await page.locator('#entregaEpi').selectOption(epi.id);await page.locator('#entregaForm button[type=submit]').click();await page.waitForSelector('.ficha-row');const ficha=(await store.list('ficha',company.id))[0];assert.equal(ficha.itens[0].epiDescricao,'CAPACETE DE SEGURANÇA');assert.equal(await page.getByRole('button',{name:/Visualizar/}).count(),0);assert.equal(await page.locator(`[data-delete-ficha="${ficha.id}"]`).count(),1);await page.screenshot({path:path.join(output,'03-fichas.png'),fullPage:true});pass('Gerar ficha mantém um documento por linha com Imprimir, Excluir e situação');
 const popupPromise=context.waitForEvent('page');await page.locator(`[data-ficha-id="${ficha.id}"]`).click();const popup=await popupPromise;await popup.waitForSelector('#signDocument');await popup.locator('#signDocument').click();await popup.waitForSelector('#verifyFingerprint');assert.equal(await popup.locator('#operationFinger option').count(),1);
 await popup.locator('#verifyFingerprint').click();await popup.waitForFunction(()=>document.querySelector('.dialog-message')?.textContent.includes('não corresponde'));assert.equal(signWrites,0);assert.equal((await store.get('ficha',ficha.id)).status,'pendente');await popup.screenshot({path:path.join(output,'04-digital-divergente.png'),fullPage:true});pass('Digital divergente bloqueia a assinatura na própria aba da ficha');
 match=true;await popup.locator('#verifyFingerprint').click();await popup.waitForSelector('dialog',{state:'detached'});assert.equal((await store.get('ficha',ficha.id)).assinaturaBiometrica.verificada,true);assert.equal(await popup.locator('#signDocument').isDisabled(),true);assert.equal(await popup.locator('.docx-epi-table tbody td:nth-child(2)').innerText(),'CAPACETE DE SEGURANÇA');assert.equal(await popup.locator('.docx-epi-table tbody td:nth-child(6)').innerText(),'Assinado Biometricamente');
 await popup.screenshot({path:path.join(output,'05-ficha-assinada.png'),fullPage:true});await popup.emulateMedia({media:'print'});assert.equal(await popup.locator('.print-toolbar').isVisible(),false);const pdf=await popup.pdf({path:path.join(output,'Ficha_EPI_Demonstracao.pdf'),format:'A4',preferCSSPageSize:true,printBackground:true,displayHeaderFooter:false});assert.equal((pdf.toString('latin1').match(/\/Type\s*\/Page\b/g)||[]).length,1);await popup.close();pass('Digital correspondente atualiza ficha e lista; PDF A4 sem botões e com nome curto');
 await page.locator(`[data-delete-ficha="${ficha.id}"]`).click();await page.locator('#deleteReason').fill('CANCELAMENTO DE DEMONSTRAÇÃO');await page.getByRole('button',{name:'Confirmar exclusão'}).click();await page.waitForSelector('dialog',{state:'detached'});assert.equal(await page.locator(`[data-ficha-id="${ficha.id}"]`).count(),0);await page.locator('#showDeletedFichas').check();assert.equal(await page.locator(`[data-ficha-id="${ficha.id}"]`).count(),1);assert.equal((await store.get('ficha',ficha.id)).status,'cancelada');pass('Excluir ficha assinada retira da lista ativa e mantém histórico com motivo');
 await page.evaluate(()=>goScreen('trabalhadores'));await page.locator(`[data-worker-bio="${worker.id}"]`).click();await page.locator('#empresaAtivaSelect').selectOption(other.id);await page.waitForSelector('dialog',{state:'detached'});assert.equal(await page.locator('[data-worker-bio]').count(),0);pass('Troca de empresa fecha a captura e não expõe trabalhadores de outra empresa');
 await page.locator('#empresaAtivaSelect').selectOption(company.id);await page.waitForSelector('[data-worker-bio]');await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(output,'06-trabalhadores-mobile.png'),fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));pass('Cadastro e botões de trabalhador cabem no celular');
 await page.locator(`[data-worker-bio="${worker.id}"]`).click();await page.waitForSelector('.bio-card img');await page.locator('dialog').screenshot({path:path.join(output,'07-galeria-mobile.png')});assert.ok(await page.evaluate(()=>document.querySelector('dialog').scrollWidth<=document.querySelector('dialog').clientWidth+1));await page.locator('.dialog-close').click();pass('Galeria de digitais cabe no celular');
 const enrollment=(await store.list('biometria',company.id))[0];await store.update('biometria',enrollment.id,{imageDataUrl:''});await page.locator(`[data-worker-bio="${worker.id}"]`).click();await page.waitForSelector('.bio-card');assert.equal(await page.locator('.bio-card img').count(),0);assert.match(await page.locator('.bio-card').innerText(),/Imagem não armazenada/);await page.locator('[data-recapture]').click();assert.equal(await page.locator('#operationFinger').inputValue(),'R_INDEX');await page.locator('dialog').screenshot({path:path.join(output,'09-cadastro-antigo.png')});await page.locator('.dialog-close').click();pass('Cadastro antigo apresenta imagem ausente e Recadastrar seleciona o dedo correto');
 await page.setViewportSize({width:1440,height:1000});await page.evaluate(()=>goScreen('empresas'));await page.locator(`[data-delete-company="${company.id}"]`).click();await page.locator('dialog').screenshot({path:path.join(output,'08-excluir-empresa.png')});await page.locator('#companyDeleteName').fill('INCORRETO');await page.getByRole('button',{name:'Confirmar exclusão'}).click();await page.waitForFunction(()=>document.querySelector('.dialog-message')?.textContent.includes('Digite o nome'));await page.locator('#companyDeleteName').fill(company.nome);await page.getByRole('button',{name:'Confirmar exclusão'}).click();await page.waitForSelector(`[data-delete-company="${company.id}"]`,{state:'detached'});await page.waitForFunction(()=>document.getElementById('appMessage').textContent.includes('Empresa excluída'));assert.ok((await store.get('empresa',company.id)).excluidaEm);assert.ok((await store.get('ficha',ficha.id)).assinaturaBiometrica.verificada);assert.ok(await store.get('trabalhador',worker.id));assert.equal(await page.locator('#empresaAtivaSelect').inputValue(),other.id);pass('Excluir empresa exige confirmação, limpa seleção e preserva ficha assinada e trabalhador');
 assert.deepEqual(errors,[]);report.passed=true;
})().catch(error=>{report.error=error.stack;console.error(error);process.exitCode=1;}).finally(async()=>{fs.writeFileSync(path.join(output,'results.json'),JSON.stringify(report,null,2));await browser?.close();server.close();});
